version: '3.6'
networks:
  cypress-network:

services:
  cypressmongo:
    container_name: cypressmongo
    image: armdocker.rnd.ericsson.se/aia/adp/mongo:4.4.1
    volumes:
      - /local/data/cypress/mongo:/data/db
    networks:
      - cypress-network

  cypressdirector:
    container_name: cypressdirector
    image: armdocker.rnd.ericsson.se/aia/adp/sorry-cypress-director:1.0.1
    environment:
      DASHBOARD_URL: http://cypressdashboard:8080
      MONGODB_URI: 'mongodb://cypressmongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      EXECUTION_DRIVER: '../execution/mongo/driver'
      SCREENSHOTS_DRIVER: '../screenshots/dummy.driver'
    ports:
      - 21234:1234
    depends_on:
      - cypressmongo
    networks:
      - cypress-network

  cypressapi:
    container_name: cypressapi
    image: armdocker.rnd.ericsson.se/aia/adp/sorry-cypress-api:1.0.1
    environment:
      MONGODB_URI: 'mongodb://cypressmongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 28081:4000
    depends_on:
      - cypressmongo
    networks:
      - cypress-network

  cypressdashboard:
    container_name: cypressdashboard
    image: armdocker.rnd.ericsson.se/aia/adp/sorry-cypress-dashboard:1.0.1
    environment:
      GRAPHQL_SCHEMA_URL: http://${API_URL:-localhost}:28081
      GRAPHQL_CLIENT_CREDENTIALS: ''
      CI_URL: ''
      PORT: 28080
    ports:
      - 28080:28080
    depends_on:
      - cypressmongo
      - cypressapi
    networks:
      - cypress-network

