echo user : $user
echo target_host : $target_host
echo adp_user : $adp_user
echo adp_group : $adp_group
echo testenv : $testenv
echo key_file : $key_file
echo env_file : $env_file
echo compose_location : $compose_location
echo service_name : $service_name
echo deployable_services : $deployable_services
echo container_name : $container_name
echo nginx_service : $nginx_service
echo restart_nginx : $restart_nginx
echo version_key : $version_key
echo adp_folder : $adp_folder
echo adp_bkp : $adp_bkp
echo env_json : $env_json
echo master_backup_location : $master_backup_location
echo database_dir : $database_dir
echo backup_location : $backup_location
echo compose_filename : $compose_filename
echo database_service_name : $database_service_name
echo database_address : $database_address
echo baseurl : $baseurl
echo mongo_master_backup_location : $mongo_master_backup_location
echo mongo_database_dir : $mongo_database_dir
echo mongo_backup_location : $mongo_backup_location
echo mongo_database_service_name : $mongo_database_service_name
echo mongo_database_address : $mongo_database_address