{
 "title": "CouchDB",
 "description": "CouchDB metrics",
 "tags": [ "CouchDB" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Database reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "couchdb_httpd_database_reads", "legendFormat": "Database reads" }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "couchdb_database_data_size", "legendFormat": "{{db_name}}" }
   ]
  },
  {
   "title": "Couchdb httpd request time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couchdb_httpd_request_time{metric=\"Max\"}"
    }
   ]
  }
 ]
}