{
 "title": "Endpoint Specific API Gateway Metrics",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "routes", "label": "Select Route", "query": "label_values(route)" },
   { "name": "code", "label": "Status Code", "query": "label_values(code)" }
  ]
 },
 "panels": [
  {
   "title": "Total Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "api_gateway_metrics_http_request_duration_seconds_count{route=\"$routes\",code=\"$code\"}",
     "legendFormat": "{{$routes}}"
    }
   ]
  },
  {
   "title": "Response Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "api_gateway_metrics_http_request_duration_seconds_sum{code=\"$code\",route=\"$routes\"}",
     "legendFormat": "Response Duration"
    }
   ]
  },
  {
   "title": "Average Response Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "api_gateway_metrics_http_request_duration_seconds_sum{code=\"$code\",route=\"$routes\"}/api_gateway_metrics_http_request_duration_seconds_count{code=\"$code\",route=\"$routes\"}",
     "legendFormat": "Average Response Duration"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "Size in KB" }
   ],
   "targets": [
    {
     "expr": "api_gateway_metrics_http_response_size_bytes_sum{route=\"$routes\",code=\"$code\"}/100",
     "legendFormat": "{{$routes}}"
    }
   ]
  }
 ]
}