{
 "title": "Generic API Gateway Metrics",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,5m,15m,30m,1h,2h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total API Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(api_gateway_metrics_http_request_duration_seconds_count)",
     "legendFormat": "{{Total API Requests}}"
    },
    {}
   ]
  },
  {
   "title": "Total 200 Responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(api_gateway_metrics_http_request_duration_seconds_count{code=\"200\"})",
     "legendFormat": "{{200 Response Count}}"
    }
   ]
  },
  {
   "title": "Total 4XX Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(api_gateway_metrics_http_request_duration_seconds_count{code=~\"4..\"})",
     "legendFormat": "{{4XX Error Count}}"
    }
   ]
  },
  {
   "title": "Total 3XX ",
   "type": "graph",
   "description": "shows how long tasks have been queued up by the event loop.",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(api_gateway_metrics_http_request_duration_seconds_count{code=~\"3..\"})",
     "legendFormat": "{{3XX Error Count}}"
    }
   ]
  },
  {
   "title": "Total 5XX Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(api_gateway_metrics_http_request_duration_seconds_count{code=~\"5..\"})",
     "legendFormat": "{{5XX Error Count}}"
    }
   ]
  },
  {
   "title": "Total 5xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_gateway_metrics_http_request_duration_seconds_count{code=~\"5.*\"}[$interval])) /sum(rate(api_gateway_metrics_http_request_duration_seconds_count[$interval]))",
     "legendFormat": "Total 5XX Error rate"
    }
   ]
  },
  {
   "title": "Count of End Points with 5XX Error ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(api_gateway_metrics_http_request_duration_seconds_count{code=~\"5.*\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Count of End Points with 4XX Error ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(api_gateway_metrics_http_request_duration_seconds_count{code=~\"4.*\"})",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Total Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_gateway_metrics_http_request_duration_seconds_count{code !=\"200\"}[$interval]))",
     "legendFormat": "Error Rate for all the API"
    }
   ]
  },
  {
   "title": "Latency ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_gateway_metrics_http_request_duration_seconds_sum[$interval]))/sum(rate(api_gateway_metrics_http_request_duration_seconds_count[$interval]))",
     "legendFormat": "Average Response Time of all the API"
    }
   ]
  },
  {
   "title": "Maximum Response Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(api_gateway_metrics_http_response_size_bytes_sum[$interval])/100 !=0",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}