{
 "title": "Performance",
 "description": "Performance metrics",
 "tags": [ "performance" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100))",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Usage root",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=\"rootfs\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk Usage /local",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/repo\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Nginx active connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Nginx Active Connections" }
   ]
  },
  {
   "title": "Backend network volume sent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(container_network_transmit_bytes_total{name=\"adp_backend\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Couch network volume sent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "increase(container_network_transmit_bytes_total{name=\"couchdb-ssl\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Wordpress network volume sent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "increase(container_network_transmit_bytes_total{name=\"wordpress-ssl\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MySQL network volume sent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "increase(container_network_transmit_bytes_total{name=\"wp-mysql-ssl\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nginx network volume sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "increase(container_network_transmit_bytes_total{name=\"nginx-portal-content-ssl\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_requests_total[15s])/15",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Backend network volume received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(container_network_receive_bytes_total{name=\"adp_backend\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Couch network volume received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "increase(container_network_receive_bytes_total{name=\"couchdb-ssl\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Wordpress network volume received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "increase(container_network_receive_bytes_total{name=\"wordpress-ssl\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MySQL network volume received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "increase(container_network_receive_bytes_total{name=\"wp-mysql-ssl\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Nginx network volume received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "increase(container_network_receive_bytes_total{name=\"nginx-portal-content-ssl\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RPS relative to Max",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(increase(nginx_http_requests_total[15s])/15)/40",
     "legendFormat": "RPS"
    }
   ]
  }
 ]
}