{
 "title": "Site use",
 "description": "Usage of ADP site",
 "tags": [ "site" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_requests_total[15s])/15",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "RPS relative to Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(increase(nginx_http_requests_total[15s])/15)/40",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Nginx active connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Nginx Active Connections" }
   ]
  },
  {
   "title": "Wordpress CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{name=\"wordpress-ssl\",container_label_org_label_schema_group=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}