version: '2'
networks:
   portal-network:

services:
   matomo:
     image: matomo
     container_name: matomo
     # volumes:
     #   - /local/data/wordpress/mysql:/var/lib/mysql
     restart: always
     networks:
       - portal-network
     environment:
       MATOMO_DATABASE_HOST: wp-mysql-ssl-test
       MATOMO_DATABASE_USERNAME: root
       MATOMO_DATABASE_PASSWORD: my-secret-pw
       MATOMO_DATABASE_DBNAME: piwik
       MATOMO_DATABASE_TABLES_PREFIX: piwik_
   testmariadbssl:
     image: mariadb:10.4.6
     container_name: wp-mysql-ssl-test
     volumes:
       - /local/data/wordpress/mysql:/var/lib/mysql
     ports:
       - "23308:3306"
     restart: always
     networks:
       - portal-network
     environment:
       MYSQL_ROOT_PASSWORD: my-secret-pw
       MYSQL_DATABASE: wordpress
       MYSQL_USER: root
       MYSQL_PASSWORD: my-secret-pw
   mockserver:
     image: armdocker.rnd.ericsson.se/aia/adp/mockserver:local
     container_name: mockserver
     ports:
       - "1080:1080"
     networks:
       - portal-network
     restart: always
   mockldap:
     image: armdocker.rnd.ericsson.se/aia/adp/mockldap-test:local
     container_name: mock-ldap
     #volumes:
     #  - /local/data/test/ldap:/home/test
     ports:
       - "38900:389"
     networks:
       - portal-network
     restart: always
     environment:
       LDAP_TLS: "false"
   testwordpressssl:
     depends_on:
       - testmariadbssl
     links:
       - testmariadbssl
       - mockldap
     # image: aia-wordpressmdocker.rnd.ericsson.se/aia/ray/aia-wordpress
     image: armdocker.rnd.ericsson.se/aia/adp/portal-wordpress:1.0.1
     networks:
       - portal-network
     container_name: wordpress-ssl
     volumes:
       - /local/data/wordpress/html:/var/www/html
       - /local/data/config/apache/adp.ericsson.se.conf:/etc/apache2/sites-enabled/adp.ericsson.se.conf
       - /local/data/certs:/etc/ssl/certs
     ports:
       - "23309:443"
     restart: always
     environment:
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: my-secret-pw
       WORDPRESS_DB_HOST: wp-mysql-ssl-test
   nginx:
     image: nginx
     networks:
        - portal-network
     container_name: nginx
     links:
       - testwordpressssl
       - nodemailerssltest
     volumes:
       - /local/data/adp/:/usr/share/nginx/html
       - /local/data/certs:/etc/ssl/certs
       - /local/data/config/nginx/nginx.conf:/etc/nginx/nginx.conf
     ports:
       - "443:443"
     restart: always
     environment:
       host: seliius18473.seli.gic.ericsson.se
       zuul.routes.wordpress.url: wordpress
   mongo:
      container_name: mongo
      image: armdocker.rnd.ericsson.se/aia/adp/mongo:4.4.1
      restart: always
      volumes:
        - /local/data/mongodb:/data/db
      environment: 
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
      ports:
        - 27017:27017
      command: --wiredTigerCacheSizeGB 0.5
      networks:
      - portal-network
   mongo-express:
      container_name: mongoexp
      image: armdocker.rnd.ericsson.se/aia/adp/mongoexpress:0.54.0
      restart: always
      links:
        - mongo
      ports:
        - 48091:8081
      environment: 
          ME_CONFIG_MONGODB_ADMINUSERNAME: admin
          ME_CONFIG_MONGODB_ADMINPASSWORD: mysecretpassword
          ME_CONFIG_BASICAUTH_USERNAME: admin
          ME_CONFIG_BASICAUTH_PASSWORD: mysecretpassword
          ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      depends_on: 
        - mongo
      networks:
        - portal-network
   adp_backend:
      image: armdocker.rnd.ericsson.se/aia/adp/adp-backend:test
      volumes:
       - /local/data/config/backend:/usr/src/app/src/config
       - /local/data/certs:/usr/src/app/src/keys/adp
      restart: always
      container_name: adp_backend
      networks:
        - portal-network
      ports:
        - 9229:9229
      links:
        - mockldap
        - mongo
      environment:
        - PORTAL_FUNC_USER
        - PORTAL_FUNC_USER_PASSWORD
        - MOCK_ARTIFACTORY_SET=https://nodemailer-ssl:3000/mockartifactory/setfolder/local/
        - MOCK_ARTIFACTORY_GET=https://nodemailer-ssl:3000/mockartifactory/local/dynamic/
        - EGS_CLIENTID
        - EGS_CLIENTSECRET
        - EGS_SCOPE
        - EGS_ACCESSTOKENURL
        - EGS_GRANT=client_credentials
      depends_on: 
        - mongo
      command: ["/bin/sh", "-c", "npm run debug" ]
   adp_backend_worker:
      image: armdocker.rnd.ericsson.se/aia/adp/adp-backend:test
      volumes:
        - /local/data/config/backend:/usr/src/app/src/config
        - /local/data/certs:/usr/src/app/src/keys/adp
      restart: always
      container_name: adp_worker
      environment:
        - BACKEND_TYPE=WORKER
        - PORTAL_FUNC_USER
        - PORTAL_FUNC_USER_PASSWORD
        - MOCK_ARTIFACTORY_SET=https://nodemailer-ssl:3000/mockartifactory/setfolder/local/
        - MOCK_ARTIFACTORY_GET=https://nodemailer-ssl:3000/mockartifactory/local/dynamic/
        - EGS_CLIENTID
        - EGS_CLIENTSECRET
        - EGS_SCOPE
        - EGS_ACCESSTOKENURL
        - EGS_GRANT=client_credentials
      networks:
        - portal-network
      links:
        - mockldap
        - mongo
      depends_on: 
        - mongo
   asciidoctorservice:
      image: armdocker.rnd.ericsson.se/aia/adp/asciidoctorservice:test
      restart: always
      container_name: asciidoctorservice
      ports:
        - 9901:9001
      networks: 
        - portal-network
   elasticsearch:
      image: armdocker.rnd.ericsson.se/aia/adp/elasticsearch:local
      restart: always
      container_name: elasticsearch
      environment:
       - discovery.type=single-node
       - bootstrap.memory_lock=true
       - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
       - /local/data/elastic:/usr/share/elasticsearch/data
      ports:
        - 48200:9200
        - 48300:9300
      networks: 
        - portal-network
   kibana:
      image: armdocker.rnd.ericsson.se/aia/adp/kibana:local
      restart: always
      container_name: kibana
      ports:
        - 48201:5601
      networks: 
        - portal-network
   nodemailerssltest:
     image: armdocker.rnd.ericsson.se/aia/adp/adp-nodemailer-mock:local
     volumes:
       - /local/data/certs:/etc/ssl/certs
     container_name: nodemailer-ssl
     restart: always
     networks:
       - portal-network

