version: '2.1'

networks:
  monitor-net:
    driver: bridge
  portal-network:
    external:
      name: ${portal_compose}_portal-network

services:

  prometheus:
    image: armdocker.rnd.ericsson.se/aia/adp/portal/prometheus:v2.10.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - /local/data/promdata:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=720h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
      - portal-network
    labels:
      org.label-schema.group: "monitoring"

  alertmanager:
    image: armdocker.rnd.ericsson.se/aia/adp/portal/alertmanager:v0.17.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: armdocker.rnd.ericsson.se/aia/adp/portal/node-exporter:v0.18.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: armdocker.rnd.ericsson.se/aia/adp/portal/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    privileged: true
    expose:
      - 8080
    command: ["--store_container_labels=false"]
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: armdocker.rnd.ericsson.se/aia/adp/portal/grafana:6.2.5
    container_name: grafana
    volumes:
      - /local/data/grafdata:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 49094
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    image: armdocker.rnd.ericsson.se/aia/adp/portal/pushgateway:v0.8.0
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  caddy:
    image: armdocker.rnd.ericsson.se/aia/adp/portal/caddy
    container_name: caddy
    ports:
      - "49094:49094"
      - "49090:49090"
      - "49093:49093"
      - "49091:49091"
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nginxexporter:
    image: armdocker.rnd.ericsson.se/aia/adp/portal/nginx-prometheus-exporter:0.4.2
    container_name: nginxexporter
    environment:
      - SCRAPE_URI=${nginx_scrape_uri}
      - SSL_VERIFY=false
    ports:
      - "9113:9113"
    networks:
      - monitor-net
      - portal-network
    labels:
      org.label-schema.group: "monitoring"
    restart: unless-stopped
