version: '2'
networks:
   portal-network:

services:
   mariadbssl:
     image: mariadb
     container_name: wp-mysql-ssl
     volumes:
       - /local/data/wordpress/mysql:/var/lib/mysql
     ports:
       - "23306:3306"
     restart: always
     networks:
       - portal-network
     environment:
       MYSQL_ROOT_PASSWORD: my-secret-pw
       MYSQL_DATABASE: wordpress
       MYSQL_USER: root
       MYSQL_PASSWORD: my-secret-pw
   wordpressssl:
     depends_on:
       - mariadbssl
     links:
       - mariadbssl
     # image: aia-wordpressmdocker.rnd.ericsson.se/aia/ray/aia-wordpress
     image: armdocker.rnd.ericsson.se/aia/adp/wordpress-ssl:1.0.1
     networks:
       - portal-network
     container_name: wordpress-ssl
     volumes:
       - /local/data/wordpress/html:/var/www/html
       - /local/data/config/apache/adp.test.ericsson.se.conf:/etc/apache2/sites-enabled/adp.test.ericsson.se.conf
       - /local/data/certs:/etc/ssl/certs
     ports:
       - "23307:443"
     restart: always
     environment:
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: my-secret-pw
       WORDPRESS_DB_HOST: mariadbssl
   nginxssl:
     image: nginx
     networks:
        - portal-network
     container_name: nginx-portal-content-ssl
     links:
       - wordpressssl
       - corsproxyssl
       - adpbackend
       - nodemailerssl
     volumes:
       - /local/data/adp/:/usr/share/nginx/html
       - /local/data/certs:/etc/ssl/certs
       - /local/data/config/nginx/nginx.conf:/etc/nginx/nginx.conf
     ports:
       - "443:443"
     restart: always
     environment:
       host: 150.132.77.180
       zuul.routes.wordpress.url: wordpress
   couchdbssl:
     image: armdocker.rnd.ericsson.se/aia/ray/adp-couchdb-ssl
     networks:
       - portal-network
     volumes:
       - /local/data/couchdb/dbData:/opt/couchdb/data
       - /local/data/certs:/etc/ssl/certs
       - /local/data/config/couchdb/local.ini:/opt/couchdb/etc/local.ini
     ports:
       - "48080:6984"
     restart: always
     container_name: couchdb-ssl
     environment:
       COUCHDB_PASSWORD: mysecretpassword
       COUCHDB_USER: admin
   adpbackend:
      image: armdocker.rnd.ericsson.se/aia/adp/adp-backend:${BACKEND_VERSION}
      volumes:
       - /local/data/test/backend:/usr/src/app/config/files
       - /local/data/certs:/usr/src/app/keys/adp
      ports:
       - "28070:9999"
       - "28060:8888"
      restart: always
      container_name: adp_backend
      networks:
        - portal-network
      links:
        - couchdbssl
   corsproxyssl:
     image: armdocker.rnd.ericsson.se/aia/ray/corsproxy
     container_name: corsproxy-ssl
     volumes:
       - /local/data/config/corsproxy/Servercorsproxy.js:/usr/share/nginx/html/Server.js
       - /local/data/certs:/etc/ssl/certs
     ports:
       - "7001:8080"
     restart: always
     networks:
       - portal-network
   nodemailerssl:
     image: armdocker.rnd.ericsson.se/aia/michael/test/nodemailer:v8.11.1
     volumes:
       - /local/data/config/mailer/servermailer.js:/server.js
       - /local/data/certs:/etc/ssl/certs
     container_name: nodemailer-ssl
     ports:
       - "3000:3000"
     restart: always
     networks:
       - portal-network
